# run command in terminal oc and ub getenforce
# check inventory file(hosts)ansible -i hosts -m ping all. (by defolt too /etc/ansible/hosts)ansible -m ping all 
- hosts: ubuntu-1
  tasks:
    - name: install apache on debian
      apt:
        name: apache2
        update_cache: yes
        state: present
          
    - name: Stand and Enable Apache
      systemd:
        state: started
        enabled: yes
        name: apache2

    - name: install unzip on debian
      apt:
        name: unzip
        state: latest

    - name: Download a Template on Debian
      get_url:
        url: https://www.free-css.com/free-css-templates/page1/education-time
        dest: /tmp/shapel.zip

    - name: Extract Template
      unarchive:
        src: /tmp/shapel.zip
        dest: /tmp/
        remote_src: yes

    - name: Move Template to /var/www/html
      shell: mv /tmp/shapel-html/* /var/www/html/
      args:
        creates: /var/www/html/gallery.html       