---
- hosts: ubuntu-1
  tasks:
  - name: install apache on debian
    apt:
      name: apache2
      update_cache: yes
      state: latest
          
  - name: Stand and Enable Apache
    systemd:
      state: started
      enabled: yes
      name: apache2

  - name: install unzip on debian
    apt:
      name: unzip
      state: latest

  - name: Download a Template on Debian
    get_url:
      url: https://www.free-css.com/assets/files/free-css-templates/download/page1/education-time.zip
      dest: /tmp/education-time.zip

  - name: Extract Template
    unarchive:
      src: /tmp/shapel.zip
      dest: /tmp/
      remote_src: yes

    # - name: Move Template to /var/www/html
    #   shell: mv /tmp/education-time-html/* /var/www/html/
    #   args:
    #     creates: /var/www/html/gallery.html       
