- hosts: CENTOS-1
  tasks:
  - name: Disable SELinux
    selinux:
      state: disabled

  - name: Install packages
    yum:
      name: "{{ packages }}"
    vars:
      packages:
        - httpd
        - unzip

  - name: Start and Enable Apache
    systemd:
      name: httpd
      state: started
      enabled: yes

  - name: Download a Template
    get_url:
      url: https://www.free-css.com/assets/files/free-css-templates/download/page1/education-time.zip
      dest: /tmp/education-time.zip

  - name: Extract Template
    unarchive:
      src: /tmp/education-time.zip
      dest: /tmp/
      remote_src: yes

